# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('entry_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('entry_short_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('entry_media', models.FileField(blank=True, null=True, upload_to='personal_website_backend/documents/')),
            ],
        ),
    ]
