# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_media',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_media_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
